services:
  # Backend API Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mealplanner-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - mealplanner-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  # Frontend React App
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mealplanner-client
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - mealplanner-network

networks:
  mealplanner-network:
    driver: bridge
    name: mealplanner-network

# Optional: Add volumes for persistent data
volumes:
  mealplanner-data:
    name: mealplanner-data
